### ISSUE TITLE
#Python# 规范1.2.1条修订建议

### ISSUE THREAD

**Issue by hi-unc1e** [Tencent/secguide#22]
https://github.com/Tencent/secguide/blob/main/Python%E5%AE%89%E5%85%A8%E6%8C%87%E5%8D%97.md#121-%E5%BF%85%E9%A1%BB%E4%BD%BF%E7%94%A8%E5%8F%82%E6%95%B0%E5%8C%96%E6%9F%A5%E8%AF%A2

![image](https://user-images.githubusercontent.com/67778054/119427192-34b71300-bd3d-11eb-928e-f7847a63fdbe.png)

【错误写法】跟【安全示例】只有注释部分不一样，建议改为更容易理解的ORM形式（如用占位符`?`），否则仍然容易产生漏洞。

**Comment by T4erg** [comment]
错误示例中将`数据`通过`%`与`SQL语句`格式化为一条字符串命令传入，存在风险；
安全示例中`SQL语句`和`数据`通过`,`分隔，将`数据`作为参数传入。

ORM形式见后文示例。

**Comment by pplmx** [comment]
f-string呢?

**Comment by Orangelxl** [comment]
建议分开写。
反例：
```python
sql = "SELECT `id`, `password` FROM `auth_user` WHERE `id`=%s " % (userid,)
cur.execute(sql)
```
正例：
```python
sql = "SELECT `id`, `password` FROM `auth_user` WHERE `id`=%s "
cur.execute(sql, (userid,))

**Comment by T4erg** [comment]
> 建议分开写。
> 反例：
> 
> ```python
> sql = "SELECT `id`, `password` FROM `auth_user` WHERE `id`=%s " % (userid,)
> cur.execute(sql)
> ```
> 
> 正例：
> 
> ```python
> sql = "SELECT `id`, `password` FROM `auth_user` WHERE `id`=%s "
> cur.execute(sql, (userid,))
> ```


曾经有位开发同学在测试时，将`WHERE id=%s " , (userid,)` 改为了`WHERE id=%s " % (userid,)`并推到线上，导致了漏洞的出现。因此两种相似的格式放在一起，来引导读者对规范进行思考与理解。避免类似的情况发生。
