### ISSUE TITLE
#Node# 规范 1.5 数据输出 修改意见

### ISSUE THREAD

**Issue by mars100** [Tencent/secguide#24]
1、问题描述
数据输出规范，属于数据业务安全范畴，并非Node语言独立特性。并浏览了Java、Go等的安全规范中，也并未包含此说明（或描述不统一）。

2、解决建议
可以新增一个数据安全类的md文档，所有服务端数据出输范畴的安全描述，都可以外联到这个文档上。

**Comment by martinzhou2015** [comment]
建议合理，已录入内部系统，讨论中。
如有其他问题或建议，可重开本议题，感谢！
