### ISSUE TITLE
#Go# 规范1.2.1条修订建议

### ISSUE THREAD

**Issue by tr3ee** [Tencent/secguide#25]
1、问题描述

[Go安全指南的1.2.1【必须】路径穿越检查](https://github.com/Tencent/secguide/blob/main/Go%E5%AE%89%E5%85%A8%E6%8C%87%E5%8D%97.md#121%E5%BF%85%E9%A1%BB-%E8%B7%AF%E5%BE%84%E7%A9%BF%E8%B6%8A%E6%A3%80%E6%9F%A5)中所列举的unzipGood例子，存在任意文件写入的问题

```Go
// good: 检查压缩的文件名是否包含..路径穿越特征字符，防止任意写入
func unzipGood(f string) bool {
	r, err := zip.OpenReader(f)
	if err != nil {
		fmt.Println("read zip file fail")
		return false
	}
	for _, f := range r.File {
		p, _ := filepath.Abs(f.Name)
		if !strings.Contains(p, "..") {
			ioutil.WriteFile(p, []byte("present"), 0640)
		}
	}
	return true
}
```

2、解决建议

> func Abs(path string) (string, error)
>  
>  Abs returns an absolute representation of path. If the path is not absolute it will be joined with the current working directory to turn it into an absolute path. The absolute path name for a given file is not guaranteed to be unique. Abs calls Clean on the result.

应当对目标路径的合法性进行校验，而不是检查是否包含`..`。

[filepath.Abs()](https://pkg.go.dev/path/filepath#Abs)自身就已经调用了[filepath.Clean()](https://pkg.go.dev/path/filepath#Clean)，因此上述函数中的`!strings.Contains(p, "..")`是无效的检查。

**Comment by tuhaolam** [comment]
已更新，感谢支持:)
