### ISSUE TITLE
希望增加一份iOS的代码安全指南

### ISSUE THREAD

**Issue by PhillipGino** [Tencent/secguide#45]
希望增加一份iOS的代码安全指南，谢谢！

**Comment by martinzhou2015** [comment]
感谢建议！iOS及Objective-C的代码安全指南正在内部完善中，后续将和社区分享，敬请留意。

如有业界好的参考材料，也欢迎通过Issues功能推荐。任何问题、建议，可以重开本单讨论，我们将会有专人跟进。
