### ISSUE TITLE
#go 规范# 1.2.1 语病

### ISSUE THREAD

**Issue by KippaZou** [Tencent/secguide#54]
![image](https://user-images.githubusercontent.com/31032511/127084825-cf6bf6bb-8160-4918-9e51-6f3f6ce7c065.png)

- `严重可能导致代码执行`，这句话应该是语病吧

**Comment by martinzhou2015** [comment]
感谢建议，经讨论本条规范描述暂不调整。如有其他建议，可重开本Issue。
