### ISSUE TITLE
#go# 规范 1.1.9 条 “slice是引用类型，在作为函数入参时采用的是地址传递” 勘误

### ISSUE THREAD

**Issue by qingchuwudi** [Tencent/secguide#57]
## 1、问题描述

文档中章节 **1.1.9【推荐】不使用slice作为函数入参** 对于slice的描述不准确，原始内容如下：

> slice是引用类型，在作为函数入参时采用的是地址传递，对slice的修改也会影响原始数据。

### 2.1、一段代码示例

```go
package main

import "fmt"

func main() {
    si := []int{1, 2, 3, 4, 5, 6, 7, 8, 9}
    fmt.Printf("%v  len %d\n", si, len(si))
    test1(si)
    fmt.Printf("%v  len %d\n", si, len(si))
}

func test1(si []int) {
    si = append(si[:3], si[4:]...)
}
```

该代码的运行结果如下：

```bash
[1 2 3 4 5 6 7 8 9]  len 9
[1 2 3 5 6 7 8 9 9]  len 9
```

### 2.2、推论结果

从代码示例及运行结果可以看出：

1. 函数内部对 slice 结构中数组的操作，对于函数外部来说部分成功了（第4个元素已经成功删除）
2. 函数内部对 slice 结构中长度（ length）的操作，对于函数外部来说失败了（第二次输出长度是9，输出元素也是9个）

#### 2.2.1、分析：

先假设 **slice做为参数是引用（或地址）传递** 成立。那么在函数内部对slice的操作应当 **完整的** 反馈在原slice上，即：函数外部slice结构中的数组（array）、长度（len）、容量（cap）这3个都应当发生与之对应的改变。

但实践后的结果与预期不符，也就是说：slice做为参数是引用（或地址）传递 **不成立**。也就是说：**slice作为参数是值传递**。

#### 2.2.2、进一步解答：

1. 问题一：既然是值传递，那为什么数组内容变了？
    因为slice整个结构是值传递，但slice中的数组是个 **指针**，在进行数据复制的过程中新的slice的数组内容使用的还是 **原指针的值**，因此函数内slice和外部的slice使用的是 **同一份数据**。

    所以函数内部对 slice 数组的操作也会反馈到函数外的 slice上。

    但是长度、容量这两个是整型数值，不是指针类型，因此复制的过程中只是复制的内容，在函数内部的操作也不会影响外部。

   附slice底层结构：
    ```go
    type slice struct { 
        array unsafe.Pointer 
        len int 
        cap int 
    }
    ```

## 参考资料及附录

- [go语言切片作为函数参数的研究](https://www.cnblogs.com/endurance9/p/10347336.html)  苏幕遮_凌枫 2019-02-01 23:49
- [slice(一)——初识底层结构](https://www.cnblogs.com/LeslieRan/articles/11910709.html)  LeslieRan 2019-12-11 16:33

---
以上是个人分析，如果大家有不同结论和分析，欢迎探讨。

**Comment by qingchuwudi** [comment]
腾讯的东西果然不靠谱，公开的文档竟然没人维护。

**Comment by tuhaolam** [comment]
@qingchuwudi 抱歉，我们跟进处理下。感谢反馈。

**Comment by martinzhou2015** [comment]
已采纳，感谢非常严谨的建议，欢迎继续一起贡献。如有其他疑问，可重开本Issue。
